-- 코드를 입력하세요
SELECT A.FLAVOR
FROM FIRST_HALF A
     LEFT JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE 1=1
AND A.TOTAL_ORDER > 3000
AND UPPER(B.INGREDIENT_TYPE) LIKE 'FRUIT%'
ORDER BY TOTAL_ORDER DESC;
