-- 코드를 입력하세요
SELECT BOOK_ID
     , TO_CHAR(PUBLISHED_DATE, 'yyyy-MM-dd') AS PUBLISHED_DATE
FROM BOOK
WHERE 1=1
AND CATEGORY = '인문'
AND TO_CHAR(PUBLISHED_DATE, 'yyyy') = '2021'
ORDER BY PUBLISHED_DATE ASC;