-- 코드를 입력하세요
SELECT
    BOOK_ID,
    AUTHOR_NAME,
    TO_CHAR(PUBLISHED_DATE, 'yyyy-MM-dd') AS PUBLISHED_DATE
FROM
    BOOK A
    LEFT JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE
    CATEGORY = '경제'
ORDER BY
    PUBLISHED_DATE ASC;